const PRIMARY_COLOR = '#1EA4CE';
const SECONDARY_COLOR = '#147594';
const BACKGROUND_COLOR = '#E5E5E5';
const WHITE = '#fff';
const BLACK = '#000';

export const BACKGROUND_COLORS = {
  DEFAULT: BACKGROUND_COLOR,
  COMPONENT: WHITE,
  LIGHT: PRIMARY_COLOR,
  DARK: SECONDARY_COLOR,
};

export const TEXT_COLORS = {
  DEFAULT: BLACK,
  TOPBAR: WHITE,
};
