const PRIMARY_COLOR = '#1EA4CE';
const SECONDARY_COLOR = '#147594';
const BACKGROUND_COLOR = '#E5E5E5';
const FLU_BUTTON = '#F2F0FD';
const WHITE = '#fff';
const COMPONENT = '#6f6f6f';
const FILTER = '#E0E0E0';

const TEXT = '#525252';

export const BACKGROUND_COLORS = {
  DEFAULT: BACKGROUND_COLOR,
  COMPONENT: WHITE,
  LIGHT: PRIMARY_COLOR,
  DARK: SECONDARY_COLOR,
  UNSELECTED: FLU_BUTTON,
  FILTER: FILTER,
};

export const TEXT_COLORS = {
  DEFAULT: TEXT,
  TOPBAR: WHITE,
  COMPONENT: COMPONENT,
  NOT_SELECTED: PRIMARY_COLOR,
  SELECTED: FLU_BUTTON,
};
